name: Build and Test Multi-Module Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build and Test Modules
        run: |
          chmod +x mvn
          ./mvn clean install

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-latest-artifact
          path: ./target  # Adjust the path based on your project structure
