name: Build and Test Multi-Module Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0  # Replace with the latest version that supports Node.js 20

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build and Test Modules
        run: |
          # Ensure the mvnw script is present in your repository
          # If not, you might need to commit it to your version control system
          chmod +x mvnw  # Set execution permissions
          ./mvnw clean install

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: my-latest-artifact
            path: ./jars # Adjust the path based on your project structure