name: Build and Test Multi-Module Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: 20
          distribution: 'adopt'

      - name: Build and Test Modules
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-latest-artifact
          path: ./main/target  # Adjust the path based on your project structure

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # Set the build context to the root of your repository
          file: ./main/Dockerfile  # Specify the path to your Dockerfile
          push: true
          tags: |
            docker push kamil571/e-commerce_spring_boot_app:latest
            docker push kamil571/e-commerce_spring_boot_app:${{ github.sha }}

          # Optionally, you can authenticate with your Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
